[build]
  publish = "."
  command = "echo 'Netlify Demo Site Build Complete!'"

[[redirects]]
  from = "/qg-sw.85aefa36f3f97d8233be.js"
  to = "/qg-sw.85aefa36f3f97d8233be.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
